apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pgdb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-pgdb@sha256:7b7f8ad58e64e6955ebea32079fb3c5b4629b95c14801b0cdd6c65fdb636204d
        name: my-nodejs
        resources: {}
status: {}
